### ISSUE TITLE
Instagram mods without paywall? 

### ISSUE THREAD

**Issue by onkoe** [purp0s3/Tweaked-iOS-Apps#8]
Do all of the Instagram mods paywall features behind a "full version"? Rocket has a giant banner at the bottom of the app, and it won't go away. Before I waste any more weekly slots, does Plus or Rhino have these? 

Do ALL of the mods have some kind of paywall? Including Twitter or YouTube? I just like downloading some good memes without ads. 

Came from a Pixel 6 Pro and still can't believe people pay for mods! On Android, they're all completely free, with no paywall and no ads! I miss Instander and ReVanced.  :(

**Comment by purp0s3** [comment]
It's been a long time since I've used Android and I too loved revanced. Their way of getting paid for all the work put into the project is through donations, making it ad-free.

Rocket devs on the other hand wanted it to be free with ads or you buy premium to get rid of them, both ways they're getting money and you still can use their tweaks for free. 

Can't blame them (or any other dev) for wanting to get paid for their work.
